version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: cron
      cronjob: "0 6 1,16 * *"
      timezone: Europe/Madrid
    rebase-strategy: disabled
    open-pull-requests-limit: 2
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: "0 6 1,16 * *"
      timezone: Europe/Madrid
    rebase-strategy: disabled
    open-pull-requests-limit: 2
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
