package com.miguelrodriguez19.safecube.core.network.data.client

import com.miguelrodriguez19.safecube.core.network.domain.model.NetworkConfig
import com.miguelrodriguez19.safecube.core.network.generated.model.AuthTokensResponse
import com.miguelrodriguez19.safecube.core.network.generated.model.VaultKeyMaterialResponse
import io.mockk.mockk
import java.time.Instant
import kotlinx.serialization.Serializable
import okhttp3.Authenticator
import okhttp3.Interceptor
import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertSame
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import retrofit2.Call
import retrofit2.http.GET

class NetworkClientFactoryIntegrationTest {
    private lateinit var server: MockWebServer

    @Before
    fun setUp() {
        server = MockWebServer()
        server.start()
    }

    @After
    fun tearDown() {
        server.shutdown()
    }

    @Test
    fun `createOkHttpClient when debug and release configs are used then never adds logging`() {
        val config = NetworkConfig(baseUrl = server.url("/").toString())

        val debugClient = NetworkClientFactory.createOkHttpClient(config)
        val releaseClient = NetworkClientFactory.createOkHttpClient(config)

        assertFalse(debugClient.hasHttpLoggingInterceptor())
        assertFalse(releaseClient.hasHttpLoggingInterceptor())
    }

    @Test
    fun `createOkHttpClient when auth components are provided then keeps them`() {
        val config = NetworkConfig(baseUrl = server.url("/").toString())
        val authInterceptor = mockk<Interceptor>(relaxed = true)
        val authenticator = mockk<Authenticator>(relaxed = true)

        val client = NetworkClientFactory.createOkHttpClient(
            config = config,
            authInterceptor = authInterceptor,
            authenticator = authenticator,
        )

        assertTrue(client.interceptors.contains(authInterceptor))
        assertSame(authenticator, client.authenticator)
    }

    @Test
    fun `createRetrofit when config is valid then uses expected base url`() {
        val config = NetworkConfig(
            baseUrl = server.url("/").toString(),
        )

        val retrofit = NetworkClientFactory.createRetrofit(config)

        assertNotNull(retrofit.callFactory())
        assertEquals(server.url("/").toString(), retrofit.baseUrl().toString())
    }

    @Test
    fun `createRetrofit when okHttpClient is provided then uses it`() {
        val config = NetworkConfig(baseUrl = server.url("/").toString())
        val client = NetworkClientFactory.createOkHttpClient(config)

        val retrofit = NetworkClientFactory.createRetrofit(
            config = config,
            okHttpClient = client,
        )

        assertSame(client, retrofit.callFactory())
    }

    @Test
    fun `createService when endpoint returns json then executes request and parses body`() {
        server.enqueue(
            MockResponse()
                .setResponseCode(200)
                .addHeader("Content-Type", "application/json")
                .setBody("""{"status":"ok"}"""),
        )
        val config = NetworkConfig(
            baseUrl = server.url("/").toString(),
        )

        val api = NetworkClientFactory.createService<PingApi>(config)
        val response = api.ping().execute()
        val request = server.takeRequest()

        assertTrue(response.isSuccessful)
        assertEquals("ok", response.body()?.status)
        assertEquals("/ping", request.path)
    }

    @Test
    fun `createJson when payload contains offset date time then parses generated field`() {
        val json = NetworkClientFactory.createJson()
        val issuedAtRaw = "2026-03-06T12:11:35.524804768Z"
        val payload = """
            {
              "accessToken":"access-token",
              "refreshToken":"refresh-token",
              "issuedAt":"$issuedAtRaw"
            }
        """.trimIndent()

        val parsed = json.decodeFromString<AuthTokensResponse>(payload)

        assertEquals("access-token", parsed.accessToken)
        assertEquals("refresh-token", parsed.refreshToken)
        assertEquals(Instant.parse(issuedAtRaw), parsed.issuedAt)
    }

    @Test
    fun `createJson when payload contains base64 fields then parses generated byte arrays`() {
        val json = NetworkClientFactory.createJson()
        val payload = """
            {
              "accountId":"4f89ab0e-453f-4be5-b261-95068f2ad6f0",
              "kekEncMaster":"AQID",
              "kekEncRecovery":"BAUG",
              "kdfAlgorithm":"argon2id",
              "kdfSalt":"BwgJ",
              "kdfMemoryKib":65536,
              "kdfIterations":3,
              "kdfParallelism":1,
              "kdfOutputLen":32,
              "cryptoVersion":"v1",
              "createdAt":"2026-03-09T12:10:45Z",
              "updatedAt":"2026-03-09T12:11:45Z"
            }
        """.trimIndent()

        val parsed = json.decodeFromString<VaultKeyMaterialResponse>(payload)

        assertEquals(byteArrayOf(1, 2, 3).toList(), parsed.kekEncMaster.toList())
        assertEquals(byteArrayOf(4, 5, 6).toList(), parsed.kekEncRecovery.toList())
        assertEquals(byteArrayOf(7, 8, 9).toList(), parsed.kdfSalt.toList())
    }
}

private fun okhttp3.OkHttpClient.hasHttpLoggingInterceptor(): Boolean =
    (interceptors + networkInterceptors).any {
        it.javaClass.name == "okhttp3.logging.HttpLoggingInterceptor"
    }

private interface PingApi {
    @GET("ping")
    fun ping(): Call<PingResponse>
}

@Serializable
private data class PingResponse(
    val status: String,
)
